export const SHOW_CONFIRM_MODAL = 'SHOW_CONFIRM_MODAL';
export const CLOSE_CONFIRM_MODAL = 'CLOSE_CONFIRM_MODAL';
export const PRODUCT_ID = 'PRODUCT_ID';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_SUCCESS_CONTINUE = 'BLOCK_USER_SUCCESS_CONTINUE';
export const USER_ID = 'USER_ID';
export const OPEN_LOADING_API = 'OPEN_LOADING_API';
export const CLOSE_LOADING_API = 'CLOSE_LOADING_API';
export const ORDER_ID = 'ORDER_ID';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const RENT_PRODUCT_ID = 'RENT_PRODUCT_ID';





