export const OPEN_LOADING_API = 'OPEN_LOADING_API';
export const CLOSE_LOADING_API = 'CLOSE_LOADING_API';
export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const CLOSE_CONFIRM_ORDER = 'CLOSE_CONFIRM_ORDER';
export const ORDER_ID = 'ORDER_ID';
export const STATE_LANGUAGE = 'STATE_LANGUAGE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ADD_TO_CART = 'REMOVE_ADD_TO_CART';
export const NEW_ID = 'NEW_ID';
export const CHANGE_LOGIN_PAGE = 'CHANGE_LOGIN_PAGE';
export const CATEGORY_ID = 'CATEGORY_ID';
export const SHOW_CONFIRM_MODAL = 'SHOW_CONFIRM_MODAL';
export const CLOSE_CONFIRM_MODAL = 'CLOSE_CONFIRM_MODAL';
export const DELETE_COMMENT_POST = 'DELETE_COMMENT_POST';
export const SET_FILTER = 'SET_FILTER';
export const ORDER_DETAIL = 'ORDER_DETAIL';














